/* Photo Frame — JPEGs are read from the chosen folder or files for this session only. */
const $=id=>document.getElementById(id);
const ui={start:$('start'),gallery:$('gallery'),detail:$('detail')};
let photos=[],mode=null,page=0,selected=0,screen='start',statusTimer=null,busy=false,touchStart=null,transitioning=false,transitionId=0,ignoreClickUntil=0,metaVisible=true;
function show(which){screen=which;Object.entries(ui).forEach(([name,node])=>node.hidden=name!==which);if(which==='start')$('resume').hidden=!photos.length;if(which!=='detail'){transitionId++;transitioning=false;$('large').style.visibility='';$('detail-figure').classList.remove('leave-next','leave-prev')}}
function status(message,sticky=false){clearTimeout(statusTimer);$('status').textContent=message;$('status').hidden=false;if(!sticky)statusTimer=setTimeout(()=>$('status').hidden=true,5000)}
function fileSort(a,b){return (a.webkitRelativePath||a.name).localeCompare(b.webkitRelativePath||b.name,'ja',{numeric:true})}
function jpeg(file){return /\.jpe?g$/i.test(file.name)||file.type==='image/jpeg'}
function exifText(data,entry,base,little){if(entry+12>data.byteLength)return '';const type=data.getUint16(entry+2,little),count=data.getUint32(entry+4,little);if(type!==2||!count||count>512)return '';const offset=count<=4?entry+8:base+data.getUint32(entry+8,little);if(offset<0||offset+count>data.byteLength)return '';let out='';for(let i=offset;i<offset+count&&data.getUint8(i);i++)out+=String.fromCharCode(data.getUint8(i));return out.trim()}
function readIFD(data,base,offset,little){const pos=base+offset;if(pos<0||pos+2>data.byteLength)return null;const count=data.getUint16(pos,little);if(count>128||pos+2+12*count>data.byteLength)return null;const fields={};for(let i=0;i<count;i++){const entry=pos+2+i*12,tag=data.getUint16(entry,little);if(tag===0x010f||tag===0x0110||tag===0x9003||tag===0x0132)fields[tag]=exifText(data,entry,base,little);if(tag===0x8769&&data.getUint16(entry+2,little)===4)fields.exifOffset=data.getUint32(entry+8,little)}return fields}
async function metadata(file){try{const bytes=await file.slice(0,256*1024).arrayBuffer(),v=new DataView(bytes);if(v.getUint16(0)!==0xffd8)return {};let pos=2;while(pos+4<bytes.byteLength){if(v.getUint8(pos++)!==0xff)break;const marker=v.getUint8(pos++);if(marker===0xda||marker===0xd9)break;const len=v.getUint16(pos);if(len<2||pos+len>bytes.byteLength)break;if(marker===0xe1&&len>14&&v.getUint32(pos+2)===0x45786966&&v.getUint16(pos+6)===0){const base=pos+8,little=v.getUint16(base)===0x4949;if(!little&&v.getUint16(base)!==0x4d4d)break;const top=readIFD(v,base,v.getUint32(base+4,little),little)||{};const sub=top.exifOffset?readIFD(v,base,top.exifOffset,little)||{}:{};return {make:top[0x010f]||'',model:top[0x0110]||'',date:sub[0x9003]||top[0x0132]||''}}pos+=len}return {}}catch{return {}}}
function captionFor(meta){let make=(meta.make||'').trim(),model=(meta.model||'').trim();if(make&&model.toLowerCase().startsWith(make.toLowerCase()))model=model.slice(make.length).trim();const match=/^(\d{4}):(\d\d):(\d\d)/.exec(meta.date||'');let date='';if(match){const month=Number(match[2]);if(month>=1&&month<=12)date=`${Number(match[3])} ${['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'][month-1]} ${match[1]}`}return {make,model,date}}

async function importFiles(fileList,nextMode,append=false){if(busy)return;const files=Array.from(fileList).filter(jpeg).sort(fileSort);if(!files.length){status('JPEGが見つかりませんでした。');return}busy=true;const created=[];try{const existing=append?new Set(photos.map(p=>p.fingerprint)):new Set(),next=append?photos.slice():[];let added=0;for(const file of files){const fingerprint=`${file.name}\u0000${file.size}\u0000${file.lastModified}`;if(existing.has(fingerprint))continue;status(`${added+1} / ${files.length} 枚目の撮影情報を確認中…`,true);const item={file,name:file.name,fingerprint,metadata:captionFor(await metadata(file)),url:URL.createObjectURL(file)};created.push(item);next.push(item);existing.add(fingerprint);added++}if(!added){status('追加する新しいJPEGはありませんでした。');return}if(!append)photos.forEach(item=>URL.revokeObjectURL(item.url));photos=next;mode=nextMode;page=append?Math.floor((photos.length-1)/6):0;showGallery();status(`${added}枚の写真を開きました。終了すると選択は解除されます。`)}catch(error){created.forEach(item=>URL.revokeObjectURL(item.url));status(`写真を開けませんでした: ${error.message||'読み込みエラー'}`,true)}finally{busy=false}}
function showGallery(){show('gallery');renderGallery()}
function renderGallery(){const total=Math.max(1,Math.ceil(photos.length/6));page=Math.max(0,Math.min(page,total-1));$('grid').replaceChildren();photos.slice(page*6,page*6+6).forEach((item,i)=>{const button=document.createElement('button');button.className='tile';button.type='button';button.setAttribute('aria-label',`${page*6+i+1}枚目 ${item.name} を開く`);const img=document.createElement('img');img.src=item.url;img.alt='';img.loading='lazy';const index=document.createElement('span');index.className='tile-index';index.textContent=String(page*6+i+1).padStart(2,'0');button.append(img,index);button.addEventListener('click',()=>openPhoto(page*6+i));$('grid').append(button)});$('count').textContent=`${String(photos.length).padStart(2,'0')} PHOTOGRAPHS`;$('album-note').textContent=(mode==='folder'?'フォルダの写真':'選んだ写真')+' · 一枚表示からは下へスワイプで戻る';$('add-files').hidden=mode!=='files';$('page').textContent=`${String(page+1).padStart(2,'0')} / ${String(total).padStart(2,'0')}`;$('prev').disabled=page===0;$('next').disabled=page===total-1}
function fitPhoto(){const img=$('large');if(!img.naturalWidth||!img.naturalHeight)return;const ratio=img.naturalWidth/img.naturalHeight;$('detail-figure').style.width=`${Math.min(innerWidth*(innerHeight>innerWidth?.90:.86),innerHeight*.77*ratio,innerHeight*1.125)}px`}
function setCaption(item){$('brand').textContent=item.metadata.make;$('model').textContent=item.metadata.model;$('date').textContent=item.metadata.date;$('camera').hidden=!item.metadata.make&&!item.metadata.model;$('detail-figure').classList.toggle('no-meta',!metaVisible)}
function openPhoto(index){if(!photos.length)return;selected=(index+photos.length)%photos.length;const row=photos[selected],figure=$('detail-figure');figure.classList.remove('enter-next','enter-prev','leave-next','leave-prev');$('large').style.visibility='';$('large').src=row.url;$('large').alt=row.name;$('large').onload=fitPhoto;setCaption(row);show('detail');if($('large').complete)fitPhoto()}
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
async function readyImage(url){const image=new Image();image.src=url;if(image.decode)await image.decode();else await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject});return image}
async function navigate(delta){if(transitioning||photos.length<2||screen!=='detail')return;transitioning=true;const token=++transitionId,target=(selected+delta+photos.length)%photos.length,row=photos[target],figure=$('detail-figure'),display=$('large');try{
  // Decode before the old photo fades. The visible element never points at an undecoded JPEG.
  await readyImage(row.url);if(token!==transitionId)return;
  figure.classList.remove('enter-next','enter-prev','leave-next','leave-prev');void figure.offsetWidth;figure.classList.add(delta>0?'leave-next':'leave-prev');
  await wait(150);if(token!==transitionId)return;
  display.style.visibility='hidden';display.src=row.url;display.alt=row.name;
  if(display.decode)await display.decode();else await new Promise((resolve,reject)=>{display.onload=resolve;display.onerror=reject});
  if(token!==transitionId)return;selected=target;setCaption(row);fitPhoto();
  figure.classList.remove('leave-next','leave-prev');void figure.offsetWidth;figure.classList.add(delta>0?'enter-next':'enter-prev');display.style.visibility='';
  await wait(340);
}catch(error){if(token===transitionId){display.style.visibility='';display.src=photos[selected].url;figure.classList.remove('leave-next','leave-prev','enter-next','enter-prev');status('次の写真を表示できませんでした。')}}finally{if(token===transitionId)transitioning=false}}
function folderSupported(){const ua=navigator.userAgent;if(!/iPad|iPhone|Macintosh/.test(ua)||!/Safari/.test(ua))return true;const match=/Version\/(\d+)\.(\d+)/.exec(ua)||/OS (\d+)_(\d+)/.exec(ua);return !match||Number(match[1])>18||(Number(match[1])===18&&Number(match[2])>=4)}
function bind(){ $('choose-folder').addEventListener('click',()=>{if(!folderSupported()){status('フォルダ選択にはiPadOS 18.4以降が必要です。更新するか「ファイルを開く」を使ってください。');return}$('folder-input').click()});$('choose-files').addEventListener('click',()=>{$('files-input').dataset.action='replace';$('files-input').click()});$('add-files').addEventListener('click',()=>{$('files-input').dataset.action='append';$('files-input').click()});$('folder-input').addEventListener('change',e=>{const files=Array.from(e.target.files);e.target.value='';if(files.length)importFiles(files,'folder')});$('files-input').addEventListener('change',e=>{const files=Array.from(e.target.files),append=e.target.dataset.action==='append';e.target.value='';if(files.length)importFiles(files,'files',append)});$('go-start').addEventListener('click',()=>show('start'));$('resume').addEventListener('click',showGallery);$('prev').addEventListener('click',()=>{page--;renderGallery()});$('next').addEventListener('click',()=>{page++;renderGallery()});$('large').addEventListener('click',()=>{if(Date.now()<ignoreClickUntil)return;metaVisible=!metaVisible;$('detail-figure').classList.toggle('no-meta',!metaVisible)});$('detail').addEventListener('click',e=>{if(Date.now()<ignoreClickUntil||transitioning||e.target.closest('figure'))return;const rect=$('detail-figure').getBoundingClientRect();if(e.clientX<rect.left)navigate(-1);else if(e.clientX>rect.right)navigate(1)});$('detail').addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.screenX,y:t.screenY}},{passive:true});$('detail').addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.screenX-touchStart.x,dy=t.screenY-touchStart.y;touchStart=null;if(dy>80&&Math.abs(dy)>Math.abs(dx)*1.3){ignoreClickUntil=Date.now()+500;showGallery()}else if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3){ignoreClickUntil=Date.now()+500;navigate(dx<0?1:-1)}},{passive:true});document.addEventListener('keydown',e=>{if(screen==='detail'){if(e.key==='Escape')showGallery();if(e.key==='ArrowRight')navigate(1);if(e.key==='ArrowLeft')navigate(-1)}else if(screen==='gallery'){if(e.key==='ArrowRight'&&!$('next').disabled){page++;renderGallery()}if(e.key==='ArrowLeft'&&!$('prev').disabled){page--;renderGallery()}}})}
function init(){bind();show('start');window.addEventListener('resize',()=>{if(screen==='detail')fitPhoto()});if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init();
